version: '3.7'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    networks:
      - sb-network
    environment:
      - POSTGRESQL_USER: sbserver
      - POSTGRESQL_PASSWORD: sbserver
      - POSTGRESQL_DATABASE: sbserver

networks:
  sb-network:
    driver: bridge